"""Make company_id non-nullable for Agent and AgentKnowledge

Revision ID: 1070f856ad7b
Revises: 4ba4182e8b9a
Create Date: 2025-11-02 15:01:13.932539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1070f856ad7b'
down_revision: Union[str, Sequence[str], None] = '4ba4182e8b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_knowledge', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agents', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agent_knowledge', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
