"""Add Company model and link agents + knowledge

Revision ID: 66f86a929550
Revises: 6d1a21e3e57f
Create Date: 2025-11-02 14:21:04.582298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f86a929550'
down_revision: Union[str, Sequence[str], None] = '6d1a21e3e57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_knowledge', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent_knowledge', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('agent_knowledge', 'company_name')
    op.add_column('agents', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.create_unique_constraint('unique_agent_per_company', 'agents', ['company_id', 'name'])
    op.create_foreign_key(None, 'agents', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint('unique_agent_per_company', 'agents', type_='unique')
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('agents', 'company_id')
    op.add_column('agent_knowledge', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agent_knowledge', type_='foreignkey')
    op.drop_column('agent_knowledge', 'company_id')
    # ### end Alembic commands ###
