"""Add company_name to agent_knowledge

Revision ID: 6d1a21e3e57f
Revises: 
Create Date: 2025-11-02 02:52:46.316613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1a21e3e57f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_knowledge', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.alter_column('agent_knowledge', 'knowledge_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('agent_knowledge_agent_id_fkey'), 'agent_knowledge', type_='foreignkey')
    op.create_foreign_key(None, 'agent_knowledge', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.create_foreign_key(None, 'conversations', 'agents', ['agent_id'], ['id'])
    op.drop_column('conversations', 'context_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('context_used', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.drop_constraint(None, 'agent_knowledge', type_='foreignkey')
    op.create_foreign_key(op.f('agent_knowledge_agent_id_fkey'), 'agent_knowledge', 'agents', ['agent_id'], ['id'])
    op.alter_column('agent_knowledge', 'knowledge_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('agent_knowledge', 'company_name')
    # ### end Alembic commands ###
